version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend:/app     
      - ./backend/data:/data
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_BASE=http://localhost:8000
